### PR TITLE
Update bundle prescription

### PR DESCRIPTION
**Pull request by tumido**
image

### CODE REVIEW

**Comment by pacospace** [comment]
Related-To: https://github.com/AICoE/meteor/issues/1

**Comment by tumido** [comment]
@pacospace can you explain? How is this related to ODH? This is an Operator Hub thing...

**Comment by pacospace** [comment]
> @pacospace can you explain how is this related to ODH? This is an Operator Hub thing... 🙂

Mmm sorry @tumido, I confused this PR, while going over all issues on meteor. Probably missing coffee after lunch :D

**Pull request merged**
