### PR TITLE
write image_url to the results for tekton chains signature

### PR DESCRIPTION
**Pull request by harshad16**
write image_url to the results for tekton chains signature
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

Related-to: https://github.com/operate-first/support/issues/438

Reference: https://github.com/tektoncd/chains/blob/main/docs/config.md#chains-type-hinting

### CODE REVIEW

**Comment by tumido** [comment]
@harshad16 would you mind doing this changes against https://github.com/thoth-station/helm-charts instead? I'd like to deprecate the pipelines specs in here as soon as possible to reduce duplicity :slightly_smiling_face:

**Comment by harshad16** [comment]
@tumido  yes,
are we already starting to use the helm-chart for the meteor?
if it still-in-progress changes, then I feel we should include this bit here as well.

**Comment by tumido** [comment]
We're not using it yet in production, but we'll switch over to it this week. :) There are some big changes comming to meteor so it'll need a full redeploy, hopefully using the "new way".

In that case I'll just merge this PR for the time being and deploy to prod.

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by harshad16** [comment]
> We're not using it yet in production, but we'll switch over to it this week. :) There are some big changes comming to meteor so it'll need a full redeploy, hopefully using the "new way".
> 
> In that case I'll just merge this PR for the time being and deploy to prod.

sounds great , thanks :100:

**Pull request merged**
